[package]
name = "assert_approx_eq"
description = "assert approximately equal"
version = "0.2.1"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/assert_approx_eq.git"
readme = "README.md"
license = "MIT"

[dependencies]
